language: go
go:
  - "1.10.x"

before_install:
  - go get -u github.com/golang/dep/cmd/dep

install:
  - make

script:
  - make

after_success:
- test -n "$TRAVIS_TAG" && curl -sL https://git.io/goreleaser | bash